### ISSUE TITLE
proxy mode

### ISSUE THREAD

**Issue by joemiller** [imkira/gcp-iap-auth#1]
I would like to use gcp-iap-auth as a proxy in front of other webapps: `[iap] -> [gcp-iap-auth] -> [backend app]`. Assuming this will work. I started working on a small utility to do this and realized I was importing so much of gcp-iap-auth that maybe it would make sense to implement proxy-mode as an option, perhaps a flag like `-proxy http://localhost:8080`.

I am happy to send a PR, time permitting, if you think this may be acceptable?

**Comment by imkira** [comment]
Sorry for the huge delay.
Yep looks great to me.
Thanks a lot for the contrib!

**Comment by imkira** [comment]
Just merged!
