### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by zwass** [imkira/gcp-iap-auth#9]
The current release is *not compatible* with IAP because it's looking for the wrong header. This was fixed in https://github.com/imkira/gcp-iap-auth/commit/91f16a3cc3e70215b64a459154f497eb54eef27d.

Users of package managers that pull down a release will be pulling a broken version of this package until a new release is created.

**Comment by zwass** [comment]
ping

This package is broken for folks using common Go dependency management systems. It will take very minimal effort to tag a new release and fix it.

**Comment by elocke** [comment]
+1 for new release

**Comment by shinkbr** [comment]
@imkira ping

**Comment by imkira** [comment]
Sorry for waiting.
Please check v0.0.5
